webAllowOthers=false
webPort=8082
webSSL=false
0=CV Comillas H2|org.h2.Driver|jdbc\:h2\:file\:C\:/Users/carla/OneDrive/Escritorio/CI2 Lab/server/data/cvcomillas;AUTO_SERVER\=TRUE;DATABASE_TO_UPPER\=false|sa
