CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS APPLICATIONS (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER_ID BIGINT NOT NULL,
  OFFER_ID VARCHAR(80) NOT NULL,
  STATUS VARCHAR(30) NOT NULL DEFAULT 'enviada',
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_APPLICATIONS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
  CONSTRAINT UQ_APPLICATIONS_USER_OFFER UNIQUE (USER_ID, OFFER_ID)
);

CREATE TABLE IF NOT EXISTS NOTIFICATIONS (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER_ID BIGINT NOT NULL,
  TYPE VARCHAR(80) NOT NULL,
  ENTITY_TYPE VARCHAR(80) NOT NULL,
  ENTITY_ID VARCHAR(120) NOT NULL,
  MESSAGE VARCHAR(500) NOT NULL,
  IS_READ BOOLEAN NOT NULL DEFAULT FALSE,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  EXPIRES_AT TIMESTAMP NULL,
  DELETED_AT TIMESTAMP NULL,
  SOURCE_KEY VARCHAR(220) NOT NULL UNIQUE
);
